---
# =============================================================================
# Manage Users Role Handlers
# =============================================================================
# Handlers for the manage_users role
# =============================================================================

- name: update locale
  ansible.builtin.command: update-locale
  changed_when: true

- name: Display user creation status
  ansible.builtin.debug:
    msg: "User {{ item.item.name }} {{ 'created' if item.changed else 'already exists' }}"
  loop: "{{ user_creation.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: user_creation is defined and user_creation.results is defined 