---
# =============================================================================
# Manage Users Role - Handlers
# =============================================================================
# This file contains handlers for the manage_users role
# =============================================================================

- name: Update locale
  ansible.builtin.command: update-locale LANG=en_US.UTF-8
  become: true
  changed_when: true
  notify: Restart SSH

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Display user creation status
  ansible.builtin.debug:
    msg: "User {{ item.name }} created on {{ inventory_hostname }}"
  loop: "{{ manage_users_users }}"
  when: user_creation is changed 