---
- name: Validate required variables
  ansible.builtin.assert:
    that: "{{ item.name }} is defined and {{ item.name }} | length > 0"
    fail_msg: "{{ item.msg }}"
  loop:
    - { name: wazuh_agent_name, msg: "wazuh_agent_name is required. Please provide it using -e 'wazuh_agent_name=your-agent-name'" }

- name: Download Wazuh agent package
  get_url:
    url: "{{ wazuh_agent_deb_url }}"
    dest: "{{ wazuh_agent_deb_path }}"
    mode: '0644'

- name: Install Wazuh agent
  apt:
    deb: "{{ wazuh_agent_deb_path }}"
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_AGENT_NAME: "{{ wazuh_agent_name }}"
  notify: restart wazuh-agent

- name: Ensure Wazuh agent service is enabled and started
  systemd:
    name: wazuh-agent
    daemon_reload: yes
    enabled: yes
    state: started

- name: Clean up downloaded package
  file:
    path: "{{ wazuh_agent_deb_path }}"
    state: absent
