---
# =============================================================================
# Configure Sudo Wheel Role
# =============================================================================
# This role configures sudo access for the wheel group
# =============================================================================

- name: Check if sudoers.d directory exists
  ansible.builtin.stat:
    path: /etc/sudoers.d
  register: sudoers_d_stat

- name: Create sudoers.d directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: '0755'
  when: not sudoers_d_stat.stat.exists

- name: Configure wheel group in sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
  register: sudoers_update
  notify: Display sudoers update status

- name: Ensure wheel group exists
  ansible.builtin.group:
    name: "{{ wheel_group_name }}"
    state: "{{ wheel_group_state }}"

- name: Configure sudo for wheel group
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/wheel
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    state: present
    create: true
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Add users to wheel group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ wheel_group_name }}"
    append: true
  loop: "{{ wheel_users }}"
  when: wheel_users is defined and wheel_users | length > 0 