- name: Initalize proxmox lxc containers
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Install sudo
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: true

    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present
        update_cache: true

    - name: Install docker
      ansible.builtin.import_role:
        name: docker
        tasks_from: install_docker.yml
