- name: Initalize proxmox lxc containers
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present
        update_cache: true

    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
