- name: Initalize proxmox lxc containers
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Comment out enterprise repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb https://enterprise.proxmox.com'
        line: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
        state: present
        backup: true
      failed_when: false

    - name: Add no-subscription repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        owner: root
        group: root
        mode: '0644'

    - name: Add Ceph community repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/ceph.list
        content: |
          deb http://download.proxmox.com/debian/ceph-quincy bookworm main
        owner: root
        group: root
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present
        update_cache: true

    - name: Install sudo
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: true

    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        groups: sudo
        append: true
        create_home: true

    - name: Allow passwordless sudo for ansible user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'
