---
- name: System Updates
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      changed_when: false

    - name: Perform apt upgrade
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
      register: apt_upgrade

    - name: Reboot if required
      reboot:
        msg: "Reboot required after system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required_file.stat.exists or apt_upgrade.changed