---
# =============================================================================
# Proxmox Common Role
# =============================================================================
# This role applies common configurations to Proxmox nodes
# =============================================================================

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Check if UFW service exists
  ansible.builtin.stat:
    path: /etc/init.d/ufw
  register: ufw_service_check

- name: Disable UFW if installed
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  when: ufw_service_check.stat.exists
  failed_when: true

- name: Check if UFW package is installed
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_os_family == "Debian"

- name: Remove UFW package if installed
  ansible.builtin.package:
    name: ufw
    state: absent
  when:
    - ansible_os_family == "Debian"
    - "'ufw' in ansible_facts.packages"

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages }}"
  when: required_packages is defined

- name: Configure timezone
  ansible.builtin.timezone:
    name: "{{ timezone | default('UTC') }}"

- name: Configure NTP
  ansible.builtin.include_tasks: ntp.yml
  when: configure_ntp | default(true)

- name: Enable unattended upgrades
  ansible.builtin.include_role:
    name: enable_unattended_upgrades
  when: ansible_os_family == "Debian"
