---
# =============================================================================
# NTP Configuration Tasks
# =============================================================================

- name: Install NTP package
  ansible.builtin.package:
    name: "{{ ntp_package }}"
    state: present
  when: ntp_package is defined

- name: Configure NTP servers
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: "{{ ntp_config_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart ntp
  when: ntp_servers is defined

- name: Ensure NTP service is running
  ansible.builtin.service:
    name: "{{ ntp_service }}"
    state: started
    enabled: true
  when: ntp_service is defined
